In [3]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print(arr)
print(arr[0][0])
print(arr[0][1])
print(arr[0][2])


print(arr[1][0])
print(arr[1][1])
print(arr[1][2]) #


[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6


In [4]:
# one dimensional array

import numpy as np
b = np.array([1, 2, 3, 4, 5])
print(b)

print(b.ndim) # to find the dimention of the array.

print(b[-1])
print(b[1:3])
print(b[1:])
print(b[1::2]) # step

[1 2 3 4 5]
1
5
[2 3]
[2 3 4 5]
[2 4]


In [5]:
#dtype to check the type for an array
a = np.array([1, 2, 3, 4, 5])
print(a.dtype)

int32


In [6]:
x = a.copy()
print(a, x)

[1 2 3 4 5] [1 2 3 4 5]


In [7]:
## reshaping 1D to 2D

a = np.array([1, 2, 3, 4, 5,6, 7, 8, 9, 10,11, 12])
b = a.reshape(4, 3)  # reshape() will convert 1D to 2D

print(b)

b = a.reshape(12, 1)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [8]:
# Joining Two arrays;
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)


[1 2 3 4 5 6]


#### sorting

In [11]:
a = np.array([['cat','ant','bat'],['cat','ant','bat']])

print(np.sort(a))

a = np.array(['cat','ant','bat', 3, 10, 5, 69, 1])

print(np.sort(a))


[['ant' 'bat' 'cat']
 ['ant' 'bat' 'cat']]
['1' '10' '3' '5' '69' 'ant' 'bat' 'cat']


#### Searching


In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 5, 4, 4])
x = np.where(arr == 4)

print(x)

(array([3, 6, 7], dtype=int64),)


In [18]:
# Find the indexes where the values are even:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr %2 == 0)
print(x)
print(x[0])




(array([1, 3, 5, 7], dtype=int64),)
[1 3 5 7]


#### Filtering an elements in an array


In [19]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]
print(newarr)

[41 43]


#### Generate Random numbers


In [32]:
# Generate a Random integer from 0 to 100.
from numpy import random

x = random.randint(100, size = (5))
print(x)

[75 28 36 44 52]


In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [34]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 4])

10


In [35]:
import numpy as np
arr = np.array([1, 2,3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [36]:
import numpy as np
arr = np.array(['banana','cherry','apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']
